spring:
  application:
    name: gamabetting-api
server:
  port: 8081
  servlet:
    context-path: /gamabetting

betfair:
  security:
    appKey: 'Szx1FGThmaNmSz9U'
    ssoToken: 'naA0Uw6cB98E4y0H/EuajiE2jE8M6CQbYNCgOsQMsZM='
  api:
    aping_url: https://api.betfair.com/exchange/betting
    rest_suffix: /rest/v1.0/
    timeout: 10000
